#    EPOS Open Source - Local installation with Kubernetes
#    Copyright (C) 2023  EPOS ERIC
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
apiVersion: v1
kind: Secret
metadata:
  name: systemsecrets
type: Opaque
stringData:
  broker_host: "netrabbit"
  broker_username: "${BROKER_USERNAME}"
  broker_password: "${BROKER_PASSWORD}"
  broker_vhost: "${BROKER_VHOST}"
  postgresql_host: "metadatacatalogue:5432"
  postgresql_username: "${POSTGRES_USER}"
  postgresql_password: "${POSTGRESQL_PASSWORD}"
  postgresql_dbname: "${POSTGRES_DB}"
  postgresql_connection_string: "jdbc:postgresql://metadatacatalogue:5432/${POSTGRES_DB}?user=${POSTGRES_USER}&password=${POSTGRESQL_PASSWORD}&targetServerType=master&loadBalanceHosts=true"
  ingestor_hash: "3F58A1895982CC81A2E5CEDA7DD9AC7009DF9998"
  api_host: "${PROTOCOL}://${LOCAL_IP}"
  api_context: "${BASE_CONTEXT}${API_PATH}"
  persistence_name: "${PERSISTENCE_NAME}"
  persistence_name_processing: "${PERSISTENCE_NAME_PROCESSING}"
  base_context: "${BASE_CONTEXT}"
  monitoring: "${MONITORING}"
  monitoring_url: "${MONITORING_URL}"
  monitoring_user: "${MONITORING_USER}"
  monitoring_pwd: "${MONITORING_PWD}"
  repotoken_default: "${REPOTOKEN_DEFAULT}"
  datametadataservice_consumers: "${NUM_OF_CONSUMERS}"
  datametadataservice_publishers: "${NUM_OF_PUBLISHERS}"
  datametadataservice_connectionpoolinitsize: "${CONNECTION_POOL_INIT_SIZE}"
  datametadataservice_connectionpoolminsize: "${CONNECTION_POOL_MIN_SIZE}"
  datametadataservice_connectionpoolmaxsize: "${CONNECTION_POOL_MAX_SIZE}"
  facets_default: "${FACETS_DEFAULT}"
  repotoken_default: "${REPOTOKEN_DEFAULT}"
  gateway_load_resources_api: "true"
  gateway_load_ingestor_api: "true"
  gateway_load_external_access_api: "true"
  gateway_load_backoffice_api: "true"
  redis_server: "redis-server"
